// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2877.ThreeCIM.subsystems;
import org.usfirst.frc2877.ThreeCIM.commands.Drive;
import edu.wpi.first.wpilibj.CANJaguar;
import org.usfirst.frc2877.ThreeCIM.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar cANJaguar1 = RobotMap.driveTrainCANJaguar1;
    CANJaguar cANJaguar2 = RobotMap.driveTrainCANJaguar2;
    CANJaguar cANJaguar3 = RobotMap.driveTrainCANJaguar3;
    CANJaguar cANJaguar4 = RobotMap.driveTrainCANJaguar4;
    CANJaguar cANJaguar5 = RobotMap.driveTrainCANJaguar5;
    CANJaguar cANJaguar6 = RobotMap.driveTrainCANJaguar6;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Drive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
